### ISSUE TITLE
Mark incremental dom as experimental

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#100]
It was recently [noted](https://groups.google.com/d/msg/closure-templates-discuss/lvVjidL0sXs/43F5jkqHLgAJ) on closure-templates-discuss that the main idom author switched projects. Therefore, incremental dom "may be stuck in an experimental state for a while".

This seems like a relatively significant staffing change since idom support was added to rules_closure. Possibly incremental_dom should be marked as experimental (or removed entirely) from rules_closure for the time being?

**Comment by jart** [comment]
Thank you for noticing this. I have tremendous respect for the attitude you're taking in this. You put a lot of hard work into getting idom merged into Closure Rules. But you're able to look past your own sweat equity and are thinking about what's best for the project.

Since someone brought up Closure Rules in that thread, maybe I should post a reply tomorrow saying that we're considering removing support. If the founder of the project is taking a step back from its development, that's a really bad sign. My personal opinion is that founders should always stand by their work until a project reaches maturity.

**Comment by hochhaus** [comment]
> Since someone brought up Closure Rules in that thread, maybe I should post a reply tomorrow saying that we're considering removing support. If the founder of the project is taking a step back from its development, that's a really bad sign.

Agreed. My previous understanding was that idom was "blessed" and imminently becoming widely supported in the closure ecosystem. However, that thread has me reconsidering my usage.

It would be unfortunate for rules_closure users to start depending on idom if the project is not appropriately staffed for future development and bug fixes. Would it be possible for you to investigate a bit further internally to understand the state of incremental dom and then make a judgement call about about the best course of action?

**Comment by jart** [comment]
One of the stated goals of this project (mentioned in the README) is to make the most conservative engineering recommendations possible. I think whether or not idom suits that goal is a decision we should all make together. I'll get in touch with the original authors and make sure they're roped into the thread. And we can have a public discussion about the future of idom, and whether or not it's a good fit for Closure Rules at this time.

**Comment by hochhaus** [comment]
Thanks, that sounds great!

**Comment by jart** [comment]
Ok I talked with the web frameworks team. They're still committed to supporting idom. They're also going to get a Closure Templates release out soon. The reason they consider it experimental, is because they haven't really battle tested it fully within Google. Considering that, do you think we should mark it as experimental too?

**Comment by hochhaus** [comment]
Thanks for the additional information. Given that, I tend to think that marking it experimental (but not removing support) is the best next step.

**Comment by jart** [comment]
Ok I'm getting ready to mark this experimental right now.

**Comment by hochhaus** [comment]
Thanks. That documentation looks great.
