### ISSUE TITLE
Current best practices for using protocol buffers in a closure project?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#108]
Thanks for the support of protocol buffers in this project @jart and @hochhaus.

I'm trying to wrap my head around the correct way to incorporate protocol buffers in my project.  Currently I make api calls from the browser to java-based server process with plain untyped JSON over a bidirectional websocket+long-polling wss: bridge. It works, but I'd like to take advantage of more strongly typed messages offered by protocol buffers.  Ultimately I'd like to scrap websockets and use HTTP/2, something along the lines of grpc, but that's premature.  In the interim, I'd be fine building a message in javascript (or java), serializing this as base64 or some other text format, passing this over the websocket, and deserializing it in java.  Main interest is in correctness (not performance which is not a limiting factor at this point).

1. Should I be using proto2 or proto3 syntax for a closure-based project?  My impression is that proto3 is a subset of proto2, so proto3 is the likely answer here.

2. The documentation for `goog.proto2.*` suggests that protoc generated classes will inherit from `goog.proto2.Message` (probably really old); the generated classes using `closure_js_proto_library` inherit `jspb.Message` instead.  Is some version of jspb.Message planned to be incorporated into closure-library (or perhaps already is)? Is there any reason to be touching goog.proto2 (or goog.proto) at all these days?

1. Migrating my project over to rules_closure would take some time.  In the interim, I'm guessing I need to generate the jspb library and include it into my exising plovr based workflow. What is the recommended way to do that? Just copy the `jspb` target and recast is as `closure_js_bin`?

**Comment by hochhaus** [comment]
> Ultimately I'd like to scrap websockets and use HTTP/2, something along the lines of grpc, but that's premature.

As you mention websockets do not currently work over HTTP/2. However, some Googlers are working on [WiSH](https://github.com/bidiweb/wish/blob/master/draft-zhu-httpbis-http2-protocol-layering-00.txt) (websocket over HTTP). It sounds like an updated Internet-Draft might be coming "[soon](https://groups.google.com/forum/#!topic/closure-library-discuss/g7dgamvU8Uo)". I know this isn't of much help to you now, but I wanted to mention it in case it modifies your future planning.

> I'd be fine building a message in javascript (or java), serializing this as base64 or some other text format, passing this over the websocket, and deserializing it in java.

This should work well. We do something very similar to it for the largest project that I work on. The only real difference is that we use [WebChannel](https://github.com/google/closure-library/tree/master/closure/goog/labs/net/webchannel) (instead of websocket) and go and c++ on the backend.

One additional point is that, in theory, JS protocol buffers should be able to be serialized to either JSON or the binary wire format. However, currently https://github.com/google/protobuf/issues/1591 is preventing meaningful use of the JSON format. Therefore, if you want to use the Protobuf v3.0.0-beta-3 alpha (in rules_closure) you'll need to use the binary format.

In the case of websocket for transmitting the serialized data I think you can send the binary data directly without base64 encoding.

For historical context, the "older" JS protobuf support was part of closure-library and called [goog.proto2](https://github.com/google/closure-library/tree/master/closure/goog/proto2). The company I work for wrote a [wrapper](https://github.com/samegoal/protoclosure) to generate *.pb.js files in the goog.proto2 syntax. That project also includes a JSON serialization/deserialization library for go. I don't know of any such open source support for Java though. Either way, now that JS is supported directly in the protobuf project I would use that code if at all possible.

> Should I be using proto2 or proto3 syntax for a closure-based project? My impression is that proto3 is a subset of proto2, so proto3 is the likely answer here.

I think all new code should use proto3 at this point.

> Is there any reason to be touching goog.proto2 (or goog.proto) at all these days?

For new code, I think goog.proto2 should not be used at all (see the historical comment above).

Goodluck!

**Comment by jart** [comment]
Thank you for the very valuable information @hochhaus. @wolfgangmeyers might be interested. Also worth mentioning that @mikesamuel has been making excellent progress open sourcing Closure Templates + protobuf support.

**Comment by hochhaus** [comment]
Thanks for the work @mikesamuel! I'm very exctied to be able to use closure templates with protocol buffers.
