### ISSUE TITLE
No longer getting most of the warnings/errors after migration from v0.2.5 -> v3.0.0

### ISSUE THREAD

**Issue by aproxs** [bazelbuild/rules_closure#161]
The BUILD file for the js binary I'm trying to generate has this binary rule:
```python
closure_js_binary(
    name = "pedantic_binary",
    entry_points = ["goog:appEntrypoint"],
    deps = [
        ":angular_lib",
        ":app_lib",
    ],
    pedantic = 1,
    language = "ECMASCRIPT5_STRICT",
    defs = [
        "--generate_exports",
        "--angular_pass",
        "--export_local_property_definitions",
        "--hide_warnings_for=externs/",
    ],
)
```

When I build it using rules_closure@v0.2.5, I get a whole bunch of ERROR messages like:
```
Attempt to use nullable type ...
```

I migrated to rules_closure@v0.3.0 and I no longer get these errors, which is an issue because the code is actually trying to use a nullable without checking.

This seems to be a rules_closure issue because I've tried both 0.2.5 and 0.3.0 with and without forcing closure compiler v20160713 and the issue consistently shows in 0.3.0 regardless of the compiler version I use.

Is this a known issue?

**Comment by hochhaus** [comment]
I think this is caused because `--new_type_inf` is no longer the default as of https://github.com/bazelbuild/rules_closure/commit/fedf10c319a93ae6e896d3b912affe4b23e05787. I think that @jart was consider re-enabling this at some point. Is that correct?

For the time being, does passing `defs=["--new_type_inf"]` give you the errors you were expecting?

**Comment by aproxs** [comment]
That fixed it! Not sure how I missed the release note.

Thanks!
