### ISSUE TITLE
Use closure workers by default

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#162]
With 0.4, bazel turned on java workers by default (https://github.com/bazelbuild/bazel/commit/490f250b27183a886cf70a5fe9e99d9428141b34). It would be nice if `rules_closure` enabled closure workers by default as well.

**Comment by jart** [comment]
@philwo are there any plans to have an option to enable workers by default? Maybe in that ctx.action execution_requirements section?

**Comment by jart** [comment]
Since https://github.com/bazelbuild/rules_closure/commit/b3e5ea89faec376be9de26f99dcd175e6ff5e3b8 we now show a helpful warning message if the user didn't put `build --strategy=Closure=worker` in his `~/.bazelrc`. That's sufficient for me right now. But I wouldn't object if you filed an issue with Bazel beseeching them to hardcode the `Closure` mnemonic into a list somewhere of workers to enable by default.

**Comment by jart** [comment]
Also take into consideration that workers still have a few rough corners, e.g. https://github.com/bazelbuild/bazel/issues/1868. So there might be a reason why the Bazel team hasn't enabled them by default yet. But still might be worth an ask.

**Comment by jart** [comment]
SGTM @philwo TYVM
