### ISSUE TITLE
README claims closure_js_binary takes a "pedantic" attribute, which it doesn't

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_closure#177]
See https://github.com/bazelbuild/rules_closure#closure_js_binary vs https://github.com/bazelbuild/rules_closure/blob/master/closure/compiler/closure_js_binary.bzl#L241 (and `ERROR: /path/to/BUILD:18:1: //pkg:target: no such attribute 'pedantic' in 'closure_js_binary' rule.` on build).

**Comment by jart** [comment]
Ah you must be using Closure Rules at HEAD rather than the latest release. Closure Rules at HEAD makes some pretty radical changes documented in https://github.com/bazelbuild/rules_closure/commit/64f93d91a11db829d8468e6a476ff047131fb927 and [here](https://github.com/bazelbuild/rules_closure/compare/0.4.0...master). It won't be tagged as 0.5.0 until I finish writing true incremental compiling, which will happen soon. 

I recommend using 0.4.0 for now. Unless your project is also multi-homed in Google's repository. If that is the case, then please track HEAD and I'll do everything I can to assist you.

**Comment by jart** [comment]
As for the pedantic flag, I should probably add that back with a deprecation warning. I'm not sure why I deleted it entirely.

**Comment by kchodorow** [comment]
Wow, okay! I updated my project to use all @foo//:foo for repos, so I'd rather not flip it back.  Happy to be on the bleeding edge if you don't mind.

**Comment by jart** [comment]
Rolling this issue into #180 where we'll be reverting the mid-release README changes.

**Comment by adam-rocska** [comment]
@jart Hi, I'm just getting started, with the closure rules. If `pedantic` support is discontinued, what are my alternatives? 

I'd have to use `defs` and be mangling with the compiler's flags itself? 

Thanks in advance for your time 😄

**Comment by Yannic** [comment]
`pedantic` is mor or less the default since #167. You should not have to do anything to use it.

I think it might be time to remove this from the readme file.

**Comment by bweston92** [comment]
PR created.
