### ISSUE TITLE
Help with integrating with rules_node

### ISSUE THREAD

**Issue by KGan** [bazelbuild/rules_closure#205]
### Env info

bazel 0.4.5-homebrew
rules_closure 0.4.0
rules_node master@ my local fork (small fix for depsets)

### Question

Hey, I have been trying to integrate rules from these two builds and I'm getting an error. I am aiming to have closure_js_binary build a bundled js binary and have rules_node's node_library/binary create a small script that will serve the js and some standard html through electron.

Here's a quick excerpt from  the BUILD file I'm writing, will list what happens below:
```
closure_js_binary(
  name = "main.bundle",
  deps = ["..."],
)

filegroup(
 name = "html"
 srcs = ['a.html']
)

node_library(
  name = 'electron_main_app',
  main = "electron_main.js",
  srcs = ["electron_main.js"],
  data = [
     ":html", ":main.bundle"
  ]
)

filegroup(
   name = "random",
   srcs = [":main.bundle"]
)

// a node app that will start electron
node_binary(
  name = "start_electron_script",
  main = "start.js",
  deps = [":electron_main_app"],
  modules = ["@electron//:modules"]
)
```

There is a part of the node_library rule that copies files from its data dependencies into some staging area it creates [here](https://github.com/pubref/rules_node/blob/master/node/internal/node_library.bzl#L93). This part fails if I do a `bazel clean --expunge` and `bazel build ..:start_electron_script`, complaining that the file is not available (the binary bundle never builds). If I run `bazel build :electron_main_app` first and check the output directories it looks fine, and then the `bazel build :start_electron_script` works fine. That is, unless I explictly run any of the other builds like `:random` other than `:start_electron_script`, it will fail, and after running any of the other builds it will work perfectly fine (changes to files in the bundle's rule cause closure compiler to rebuild the binary, and I see it fine).

I am still reading docs and my understanding of bazel isn't really complete to any degree. I only have a small inkling/intuition of how the phases work, how rules work, etc. Let me know if it is a blatantly obvious issue... Thanks in advance.

**Comment by jart** [comment]
We unfortunately provide very little currently in terms of Node integration. Integrating Node with Bazel is extraordinarily difficult, because there's so many tiny packages. pubref/rules_node tried to make it simple, but traded hermeticity, determinism, linear complexity, sandbox support, and sha256 checksums in the process. For these reasons, interop is most likely not a feature we'd consider.

**Comment by KGan** [comment]
I see, thanks for the insight.

**Comment by pcj** [comment]
Hi @KGan, I'm currently re-writing rules_node to use yarn rather than npm which will address some of the non-determinism that seems built-in to npm.  Feel free to post an issue there and we'll work it out.  Excited to see what you come up with re: bazel, node, electron.

**Comment by jart** [comment]
@pcj I would recommend syncing up with @alexeagle who is doing similar work.

**Comment by alexeagle** [comment]
Hey @pcj I'd like to sync up,  I considered posting an issue to your repo, but I'm taking a totally different approach.
Instead of making the WORKSPACE file contain a copy of what users have in their package.json file, and using bazel as the package manager, I just call yarn with the user's package.json. Then the resulting node_modules directory is treated as one big filegroup() rule, so you don't need any node_module() rule. Instead node_binary() (and any other binary or test that depends on running node) will get the entire node_modules in the runfiles.
This is a tradeoff, making the rules less fine-grained and depending on an external package manager. On the other hand it more closely matches the existing workflow for nodejs. I am treating bazel as just a build tool that plugs into the ecosystem, rather than as a build tool plus package manager.

**Comment by KGan** [comment]
@pcj @jart @alexeagle  Not necessarily on your current topic of discussion, but my issue ended up being much simpler and not so fundamental (probably). Turns out data files were just not being used in the actions produced by node_library, so I suppose when building the node_binary rule the analysis of the dependent node_library rule is that its data files weren't needed. https://github.com/bazelbuild/bazel/issues/2665 

I'd love to follow your progress on this though :)

**Comment by pcj** [comment]
Hi @alexeagle sounds good.  

One item I'm unclear about your proposed approach is you still need `yarn add` in a repository rule when fetching external files over the network, right?  You don't want to be getting dependencies ad-hoc during the execute phase.  Also not in love with creating separate tools that have to be run as a pre-processing step to generate BUILD files, but this has worked out in practice so I'm not absolutely against it.

Anyhow, interested to check it out when you are ready to share it.  If we can work together to get something generally usable on the bazelbuild tree, I'm game to help.  Always better to have more than one maintainer.

**Comment by pcj** [comment]
Also I'm doing alot of typescript these days so I'd love to see the worlds of closure + typescript married up well with clutz and tsickle as you are working towards.
