### ISSUE TITLE
Deprecate phantomjs?

### ISSUE THREAD

**Issue by x1ddos** [bazelbuild/rules_closure#256]
The `closure_js_test` is currently quite limiting being stuck with phantomjs.

Aside from inability to run on real browsers, it also leads to all sorts of issues. For example, see https://github.com/webcomponents/custom-elements/issues/70. Even if phantomjs' webkit dependency were upgraded to a more recent version, this would still run JS tests only on phantom.

Wouldn't it be better to use chrome headless or firefox, or, better yet, reuse https://github.com/bazelbuild/rules_webtesting?

**Comment by erickj** [comment]
Also, phantomjs is abandoned as of 3/3/2018

https://github.com/ariya/phantomjs/issues/15344

**Comment by x1ddos** [comment]
Here's how I replaced phantomjs-based tests with rules_webtesting, in case it's useful:
https://github.com/googlecodelabs/codelab-elements/blob/de703057853e9c416dcd646db1656323eb770d8e/tools/defs.bzl#L156

**Comment by jart** [comment]
rules_webtesting is the officially blessed and maintained solution.

PhantomJS still works and will continue to work forever, because it was distributed in a brilliant manner, and is not subject to the sorts of concerns that require ongoing maintenance. It continues to offer significant value for those seeking to test their JavaScript works in very old browsers. It shall continue to do so.

**Comment by x1ddos** [comment]
Well, `closure_js_test` rule to provide javascript testing only for very old browsers and not for modern ones sounds absurd to me.

In other words, there's nothing in rules_closure repo which would allow javascript testing with modern browsers. Would you please consider reopening this issue and renaming it to something like "Support JS testing with modern browsers"?

**Comment by jart** [comment]
Your concerns have been taken into consideration. rules_closure is one part of a larger ecosystem. We support rules_webtesting too.
