### ISSUE TITLE
Nothing to build with closure_proto_library

### ISSUE THREAD

**Issue by v48** [bazelbuild/rules_closure#287]
I currently have proto BUILD defined with the following:

```bash
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "a_proto",
    srcs = ["a.proto"],
)

closure_proto_library(
    name = "a_closure_proto",
    deps = [":a_proto"],
)
```

when I run `bazel build //repo/protos:a_closure_proto`

I do not get any output in `bazel-bin` or `bazel-genfiles`
```bash
INFO: Analysed target //repo/protos:a_closure_proto (0 packages loaded).
INFO: Found 1 target...
Target //repo/protos:a_closure_proto up-to-date (nothing to build)
INFO: Elapsed time: 0.291s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

*Is there something im missing?*

**Comment by Yannic** [comment]
Your BUILD file is correct.
Bazel will only run actions if another target/action depends on them or if the outputs are "returned by a target" (i.e. if they are in `DefaultInfo`). Since `closure_js_library` doesn't produce any artifacts unless something depends on them, that's also the case with `closure_proto_library`. If any `closure_js_{binary,test}` (transitively) depends on you proto target, then Bazel will execute the actions generating the `.js` file of the `.proto` file and you'll see the files in `bazel-out`.

Unfortunately, I'm not sure if we can (or should) change this behavior. Maybe @jart can provide some insights into why it was implemented this way.

**Comment by pcj** [comment]
This is the correct behavior as @Yannic explains.  The only tangible form of closure artifacts is after it goes through the compiler (which only occurs within a `closure_js_{binary,test}` rule).  Otherwise there is no work to be done.
