### ISSUE TITLE
goog.exportSymbol and entry_points

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#334]
I'm evaluating a move from plovr to rules_closure for our JS building needs. So far rules_closure seems like it will provide much faster builds, as well as the capability to use much better compile-time checks. Thanks for developing it!

I ran into a stumbling block. In our code, we use a mix of `goog.module` and `goog.provide`, and we use `goog.exportSymbol` to specify entry points that are then invoked by the containing page:

```
goog.module('corp.landingpages.async.main');

function init(options) {
  ...
}

goog.exportSymbol('ModuleAsyncServing.Initialize', init);
```

It seems like `rules_closure` does not honor the `goog.exportSymbol` declaration and requires me to specify it in the entry_points property of the containing binaries:

```
closure_js_binary(
    name = "async_bin",
    compilation_level = "ADVANCED",
    entry_points = ['corp.landingpages.async.main'],
    language = "ECMASCRIPT5",
    output_wrapper = "(function(){%output%})();",
    deps = [":async_lib"],
)
```

Some of our JS bundles are used across dozens of pages, so the book-keeping required to keep `entry_points` in sync with the code seems not insignificant. 

Can you confirm that the recommended way to accomplish this is to replace `goog.exportSymbol` with `entry_points`, or else can you advise on any alternatives that I might be missing? 

Thank you!
Rob

**Comment by gkdn** [comment]
Closure provides different [dependency modes](https://github.com/google/closure-compiler/wiki/Managing-Dependencies).
By default closure_js_binary uses "LOOSE" mode. In LOOSE mode, Closure uses the entry points to drop unused code. You could change this behavior by explicitly stating which dependency_mode; e.g. ```SORT_ONLY``` however I would not recommend that since you might end up having less optimizations and more compile time.

Also keep in mind that, you only need to provide an entry point if and only if it is not reachable from existing entry points and if it uses goog.module; so you don't list every file. You can also have single entry point that just goog.requires others.

With respect to goog.exportSymbol and dependency mode interaction, I would assume that's expected and they won't be considered as entry points by default in LOOSE mode but that's something that you need to check with Closure compiler.

Since this is more specific to Closure compiler than the rules, I recommend you using their support channel for better support.
