### ISSUE TITLE
JSX Support / Custom compiler passes

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#407]
I would like to use rules_closure with the JSX custom compiler pass developed here:
https://github.com/mihaip/react-closure-compiler

Can anyone provide pointers on how to do such a thing? Would rules_closure be interested in  a pull request adding JSX support to closure_js_library? 

Here's my take on how to approach this:

- Package it with closure compiler and use that custom jar instead of trying to arrange for it to be on the classpath.
- Allow .jsx and .js files in closure_js_library
- Probably other things, but I'm not sure.

Anyone have ideas? Is this a bad idea?

**Comment by sgammon** [comment]
as a user i am very much against this lol

**Comment by sgammon** [comment]
like, @robfig, i know how you might go about implementing this, but surely you would want idom-style technologies instead of virtual-DOM and JSX? idk

**Comment by robfig** [comment]
Caveat - I don't write much front-end code, I'm just a tooling person supporting others, so my opinions are informed by relatively little hands-on experience writing the code, but a lot of code review / maintenance / refactoring to work with build tools. 

What idom-style technologies are you referring to? If you mean the Google one that works with Soy templates, that's not much of an alternative. React's big innovation was having a structured model for components that can compose. Folks say they have X hundred components used throughout their application. Components are testable and often have unit tests. They are a real thing, and I think that's great. I haven't seen any other front-end programming models find success like this, and it seems to be well deserved. My understanding is that the idom provides a DOM-updating mechanism, not a component model. 

Regarding Virtual DOM vs incremental dom - I feel like a lot has been made of this, but from my perspective the performance aspect is not at all important for what we do with front-end. My main priorities are developer productivity and integration with Bazel. 

Regarding Templating - I think Soy is outstanding, but after championing the development of a Soy-based incremental-DOM solution for components, I do not think that is the way to go. The ability to incorporate event handlers tightly into templates is a pretty big advantage. Without that, there is a ton of JS code that makes assumptions about the DOM structure and has to reach in with selectors to grab stuff. That sort of thing is brittle and is much less common in React components.

Anyway, hopefully I haven't totally misunderstood your note. 

My current goal is to get our codebase working with JSX, Closure Compiler, Bazel, and IDE support that understands imports. I posted here looking for advice earlier:
https://groups.google.com/d/msg/closure-compiler-discuss/9yJE3VmWb2M/cz6yuDMrEgAJ

Seems like I have to solve one of two barriers:
- Get IDEs to understand goog.module declarations and show the same helpful information around them, probably by implementing LSP
- Migrate to ES6 module imports, which has good editor support. Issue is that imports include the file extension (e.g. import 'path/to/component.jsx'), so Closure Compiler would need to be updated to accept .jsx files instead of our current approach of preprocessing them to .js before feeding them in (since that step breaks the import statement).

If you have any recommendations, I'm all ears!

**Comment by sgammon** [comment]
I guess my only thing is, there isn't anything preventing use of JSX. It fits at a higher level of abstraction than the Closure compiler. I'm not sure if the two are usable together, outside of `lenient` mode.

When I say `idom` is an alternative, it's because it is. Virtual DOM is the same thing as `idom` or other DOM rendering/reduction approaches, it just chooses not to keep an entire parallel structure in memory to facilitate the rendering process (the "virtual DOM" itself is what I'm talking about).

In `idom`, the "virtual DOM" is just the DOM, because you're merging against the current state of the page, not the current state of the "virtual DOM."

In any case, these approaches are similar but different because one requires what is the equivalent of a VM for templates in your browser. As in, templates call each other, but those calls don't result in DOM changes, they result in virtual DOM changes, which are then rendered into the DOM.

Obviously `idom` is just a component, and it has taken quite a bit to get it to work for us. But we are very, very happy with it. It's super fast, uses almost no memory, and fits well into nearly any application architecture.

**Comment by sgammon** [comment]
Frankly we're talking about two things here: render flow/planning, and components. Shadow DOM is another approach that would get you where you want to go.

Shadow DOM, just like virtual DOM, is not inherently incompatible with `idom`, though. You would just be rendering components in `idom`, from Soy, that are custom elements, which themselves invoke Shadow DOM semantics, including the ability to bind on and off the object without using selectors.

With this approach, for instance, you could manage to:
1) Stay very close to web standards
2) Still use all your favorite JS features without the abstraction of JSX
3) Not use selectors as the primary method for binding in the DOM
4) Not have to create a whole virtual DOM tree copy to facilitate basic rendering

There are some caveats to this approach. We encountered an issue recently where `idom` would trample attributes added in JS after-the-fact. It turns out there are mechanisms in `idom` to handle that so we're now using those.

All in all we feel very supported and empowered by the Soy/`idom` pair, so long as you can get it working on `HEAD`.

**Comment by sgammon** [comment]
One thing you could look at... I know @jart's awesome [use of `rules_closure` in Tensorboard](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/vz_sorting/BUILD) uses the Polymer/Vulcanize stack to do custom elements. The approach would allow you to use shadow DOM in concert with `idom`/Soy.

Take a look, otherwise, good luck with your project. As a user I would personally be against including JSX-specific features in `rules_closure`, if only because they don't exist on the same level of abstraction. We maintain our own fork of `rules_closure` just to get it to work well with the new `idom`, so, it would be a little annoying to see React technologies make it into `master` before good integration with Closure's own ecosystem.

Tbh it would probably feel more natural anyway to compile your templates with JSX, and then move those sources through `rules_closure` as JS (Closure Compiler doesn't like non-JS although it's getting there), although, that won't work mixing JS and JSX.

**Comment by sgammon** [comment]
@robfig, one more thing. w.r.t. custom closure passes, those can be setup in the `ClosureWorker` which provides config to GCC.

**Comment by robfig** [comment]
Thanks for your perspective and links to related work. A year ago when we were looking into idom, there was almost zero resources online; I'd love to read a detailed blog post on how you got everything to work, if you have the desire to publish something someday. 

Regarding this particular item, we figured out a way to solve all of our problems using a preprocessing pass, so we're still feeding regular JS to rules_closure (phew).

**Comment by sgammon** [comment]
i understand how you feel, lol

i would be happy to put together a blog post and perhaps a guide to using our fork, if `rules_closure` won't accept the PRs. great idea and good luck with your stuff, glad to hear it's working
