### ISSUE TITLE
rules_closure creates a maintenance burden for Closure Library authors

### ISSUE THREAD

**Issue by concavelenz** [bazelbuild/rules_closure#412]
Build files like https://github.com/bazelbuild/rules_closure/blob/master/closure/library/ui/BUILD are being maintained separately from Closure Library and make it possible for Closure Library maintainers to break rules_closure simply by introducing a new dependency.

**Comment by gramic** [comment]
It is also a burden to the users like me, who want to keep up to date with the latest Closure Tools. However, rules_closure helps much more then it burdens me.

Maybe I can help if I get to watch closely Closure Library changes and update the rules with pull requests in faster rate.

**Comment by Yannic** [comment]
I raised this issue [over a year ago](https://groups.google.com/forum/#!topic/closure-rules-discuss/8bwlPD8G6wY), but here we still are.

@concavelenz Would the Closure Library team be open to adding BUILD files in their repository? I can contribute them if necessary.

**Comment by Yannic** [comment]
(For reference: google/closure-compiler#3461 google/closure-templates#190)

**Comment by sgammon** [comment]
I believe @robfig has added a way to generate these files with Gazelle...

**Comment by concavelenz** [comment]
@Yannic yes they are, it is just a question of getting the time to get the plumbing setup to maintain them.

**Comment by robfig** [comment]
You can try out my Gazelle fork.
https://github.com/robfig/bazel-gazelle/tree/js

Check that out (the `js` branch), then `bazel build cmd/gazelle:gazelle_js` and run that from the root of your repo. 

I mean to transition it to a standalone module instead of a fork, but I'm not sure when I'm going to get to that.

**Comment by alexeagle** [comment]
@robfig that looks great, I am planning to pick up this task and make these BUILD files part of the closure-library distribution. I'll try out your gazelle plugin.

**Comment by alexeagle** [comment]
@robfig I tried that out yesterday, totally works. We are thinking about a couple things though:
- it would be good if closure-library can be consumed without rules_closure since the latter is kinda unmaintained, compared with rules_nodejs that supports the entire JS ecosystem. So I think we should use the `js_library` rule from rules_nodejs - I need to promote it to the public API first
- We have BUILD files internal at Google for closure-library. @nreid260 points out that these are the only ones which are really tested, and the naming convention of files is not 100% related to the goog.module names. So maybe we should just scrub/publish our BUILD files with closure-library releases

**Comment by robfig** [comment]
It makes sense if you want to support `rules_nodejs` since it's more popular. But, if you publish BUILD files with `js_library` rules, would that address `rules_closure` BUILD file maintenance, or is that a "won't fix" response? It does seem like publishing your internal BUILD files would be the ideal solution -- even if it doesn't use rules_closure, I suppose it should be easy to mechanically convert them or something.

FWIW, I use both `rule_nodejs` and `rules_closure`, and I find they work perfectly well together. We process JSX to JS using babel, and use the output as a `closure_js_library`. Closure's per-file linting, suppressions, and strict dependency checking are outstanding for maintenance and it's very easy to configure the compilation using `closure_js_binary`. We have a monorepo of ~100 JS applications so this is the ideal use case for it I suppose. I only mention this because I don't agree that the rules are competitive with each other -- `rules_closure` compiles and `rules_nodejs` does everything else. 

Regarding the staffing of rules_closure, it could definitely use some help. I'm not sure if you have any say in the matter, but I think there are a couple capable folks around that would be willing & able to help with that if given access. 

Thanks for looking into this!

**Comment by alexeagle** [comment]
FYI I got this working, just a snapshot of closure-library
https://github.com/google/closure-library/compare/v20190415...alexeagle:mv_library_build
which is consumed by rules_closure
https://github.com/bazelbuild/rules_closure/compare/b2a6fb762a2a655d9970d88a9218b7a1cf098ffa...alexeagle:mv_library_build
and it works when used by a typical rules_closure user:
https://github.com/jleyba/js-dossier/compare/master...alexeagle:mv_library_build

still working out the steps for how we could publish closure-library looking like this.
