### ISSUE TITLE
Possibly updating Closure Library to `v20210601`? :)

### ISSUE THREAD

**Issue by sampajano** [bazelbuild/rules_closure#528]
We have a recent change in https://github.com/grpc/grpc-web which requires the newest version of closure library ([`v20210601`](https://github.com/google/closure-library/releases/tag/v20210601)). I wonder how much effort would it be for rules_closure to upgrade to it (current version is [`20191027`](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L695-L706) if i'm reading correctly? :)) Thanks a lot in advance! :)

**Comment by gkdn** [comment]
The main issue is https://github.com/bazelbuild/rules_closure/issues/516

To be honest, I don't know the effort required since I don't know all the implications of goog.requireType and have not spent much time around the script that generates the BUILD targets .

Being said that; that issue needs to be resolved one way or the other for going forward.

**Comment by sampajano** [comment]
Thanks so much for the context, Goktug! I'll follow-up with you on #516 :)

@Yannic Hey Yannic! Cc'ing you here because @stanley-cheung has mentioned you've helped with similar issues in the past.. and in case you have some ideas too :)
