### ISSUE TITLE
How is this different/same as plovr?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#77]
I'm just looking at this project and trying to figure out if it replaces plovr.  At first glance it seems like there is overlap with this project and what @bolinfest had intended many years ago with plovr.  

One of things that I can't give up with plovr is build times.  the `plovr serve` command is the only good way I know of keeping a JVM hot with the closure compiler.  With a cold start JVM my build times are on the order of 30s, but with plovr serve after the first compile they're about 4-5s.  

Does this project somehow replicate the `plovr serve` command? Again the crux issue is keeping the JVM running between compiles.

**Comment by pcj** [comment]
Also, are groups within google using this?

**Comment by hochhaus** [comment]
Good question about minimizing compile times via a hot JVM.

> Also, are groups within google using this?

With the [0.1.0 release](https://github.com/bazelbuild/rules_closure/releases/tag/0.1.0) @jart stated:

> This release brings Closure Rules to a level of quality that it's now been adopted by a 100k+ LOC codebase.

That is almost certainly a group within Google.

**Comment by damienmg** [comment]
@pcj: Bazel is a curated version of the build system that is used inside Google. Blaze (bazel inside Google) has a >20k engineers daily active users.

Closure rules are a project started to replace the internal JS rules used inside Google (not open-sourced for a variety of reasons, mostly because they are too specific to how we do JS development at Google). @jart is a talented engineer from Google that developed those rules to work for the need of her team (and other teams). The closure rules provided for Bazel have reached such a level that they can safely be used to support a variety of project. As a lead of the Bazel project, I strongly encourage people to tries those rules out and tell if anything is wrong so those rules can be used outside of Google.

For keeping the JVM hot, we do have a worker strategy, See http://www.bazel.io/blog/2015/12/10/java-workers.html. I think this is not yet used for closure rules but it can definitely be used. @jart should talk to @philwo to use it.

**Comment by jart** [comment]
@damienmg I'm really touched. Thank you for your kind words of support.

@pcj [Plovr](http://plovr.com/) was written by @bolinfest back in 2010 after he left Google. (He's also the author of [Buck](https://buckbuild.com/) which is a Blaze clone we used before Bazel became open source.) Plovr had a lot of potential, but it never really [caught on](https://www.google.com/trends/explore#q=plovr%2C%20gulp%20js%2C%20grunt%20js). Most JS devs use Gulp or Grunt. This is probably why @bolinfest publicly announced in 2013 that he was taking a step back from the project. He hasn't made a commit since 2014.

Closure Rules has two disadvantages compared to Plovr:

1. No out of the box web server. But you can still do interactive development. You just have to write the web server yourself and use raw sources mode. [closure_js_deps](https://github.com/bazelbuild/rules_closure#closure_js_deps) is designed to make this possible. In maybe a month or so, I'll probably write an example Guestbook application for App Engine that shows how a real project can be written with Closure Rules. I don't have any plans to write development web  server / web framework stuff for the foreseeable future. The focus right now is on creating the best JS build system.

2. No binary splitting a.k.a. modules support. This is something Plovr does really well. The vanilla Closure Compiler can also do this. But Closure Rules can't *at all*. Fixing this is pretty high on my list of priorities.

Closure Rules has many advantages compared to Plovr. Most of them are inherited from Bazel. The rules are designed to scale to a repository with petabytes of code, where thousands of engineers are changing everyone's projects constantly, and almost no one has any clue how to actually run the code they're changing. So Closure Rules is really good at automated unit testing and screenshot testing. If you ever wanted to do web development without using a web browser, then you're going to love Closure Rules. This project also has a long term focus on being extremely strict and safe by default.

If you're wondering who uses Closure Rules internally at Google, I could be slightly disingenuous and say:

![fttblia](https://cloud.githubusercontent.com/assets/49262/15624504/2ce3c85a-2457-11e6-9825-41fc34ec0f02.gif)

Because Closure Rules is basically just a polished up version of the internal build rules we've been using for years. But only one major project at Google is currently using the Closure Rules dialect, which is situated on GitHub. Internally, we have simple build macros that translate Closure Rules into the legacy rules. Outside Google, at least two other companies have signed on board with Closure Rules and have contributed to its development.

For comparison, there isn't a single project at Google that uses Plovr as its build system. Only one team at Google has Plovr configs checked into the codebase. They appear to be used for its development server capabilities. But much more robust tools actually exist internally for this, which would take an incredible amount of effort to be made open source.

As for build times, I can't imagine JVM lag is the biggest problem. Closure Compiler takes 8000ms to compile a single function. If you turn off all the browser externs with `--env=CUSTOM`, it still takes four seconds. Closure Compiler uses so many resources, that compiling a humongous codebase will nuke my 32gb Xeon workstation if I don't use `--local_resources=8000,4,1.0`. Something is rotten in the state of Denmark. I'm probably going to break out a profiler soon and figure out what's wrong with JSCompiler.

But things aren't as dismal as I make them out to be. This entire project builds / tests just fine on a Travis CI VM with 256mb of RAM. You just have to be careful about how you tune Bazel.

I can also look into using the Bazel worker thing @damienmg mentioned. Maybe I can hack the Closure Compiler into maintaining a shared persistent cache of individually compiled JS files. I want our users to be able to do cool things, like statically compile large numbers of language-specific binaries optimized for each browser, without having to pay for a massive build farm. I also want test commands to run really fast, without sacrificing compilation.

**Comment by pcj** [comment]
Thanks @hochhaus @damienmg @jart for the detailed responses.  I certainly like the idea of browserless development and I can see how the design of bazel + rules_closure encourages (or perhaps a stronger word than that, but not quite *requires*) test driven development.  

If there is a suggested starting point / getting started repo / hello world closure app that models the ideal / recommended methodology of running, testing, and viewing/evaluating the test output a closure app, I'd like to learn more about that, try it out, and contribute back if possible.

**Comment by jart** [comment]
Right now the closest thing we have to examples are the [test directories](https://github.com/bazelbuild/rules_closure#examples). We currently don't have any examples demonstrating how to properly build real apps with these rules. But I'd be happy to write some for you.

But it would help if I could better understand what you're looking for.

For example, maybe I could write a guestbook application using the following stack:

1. Run on AppEngine Java
2. Use Java, Guice, and Jersey as the web framework
3. Use Objectify to talk to Cloud Datastore
4. Define API endpoints that transmit Protocol Buffers as JSON
5. Soy templates render Protocol Buffer data structures
6. Compile one Soy template to Java so it can be rendered on the backend as the initial [SPA](https://en.wikipedia.org/wiki/Single-page_application) page
7. Rest of app is implemented in Closure JavaScript on the client side, with all the Soy templates compiled into this one binary, that uses XHR requests to get the Protocol Buffers with guestbook data so it can render them on the client side
8. MAYBE incorporate Material Design stuff somehow

That development stack is pretty much the *closest* open source equivalent I can think of to how Google builds web applications internally.

Whether or not I'll be able to do this, depends on how ready proto3 is. I'd also really love to use Dagger 2 instead of Guice, but I don't know if I'd be able to get it to work well with JAX-RS Jersey.

Is this an acceptable stack to you? Is that a stack you'd want to learn? If not, what would you prefer? Also: can you think of a simpler example I could build that would offer you 80% of the same value?

**Comment by hochhaus** [comment]
> Soy templates render Protocol Buffer data structures

This would be AMAZING. However, I think the necessary open source code is [not released yet](https://groups.google.com/forum/#!topic/closure-templates-discuss/PAXx6SKMm5Y).

**Comment by jart** [comment]
That is so dismal. It looks like I'm going to have to fight to get that open sourced. Closure Templates are pretty much the saddest thing if you can't use them with Protocol Buffers.

**Comment by hochhaus** [comment]
Thanks! I believe that getting that code open sourced would be another game changer for this tool set.

**Comment by jart** [comment]
I agree. 90% of the problems I've encountered doing pure open source Closure development, stemmed from a lack of Protocol Buffers. In fact, if we exclude algorithmic and systems stuff, I wouldn't be surprised if 90% of programming problems *in general* stem from not using Protocol Buffers for everything.

@wolfgangmeyers filed https://github.com/google/protobuf/issues/1368 which basically amounts to generating `@externs` for the JSON definition of protocol buffers. If that were written, it could also make Protocol Buffers work for Closure Templates compiled to JS only, in a suboptimal way.

**Comment by pcj** [comment]
So I was able to get things working, I put up a [test repo](https://github.com/pubref/rules_closure_demoapp), please comment if there are glaring errors on how the repo is setup.  I'll plan to fill it out further as a more useful example.  @robfig https://github.com/robfig/undertow-bazel-closure-tools was also a helpful resource.  

The demo application you have proposed sounds awesome. 

My primary initial is interest is getting the test/develop cycle right and I'd like to pattern it on best practices within google.  With plovr the interactive development *is* nice, but it makes it too easy to just keep writing "production" code and not enough tests.  So I'd like to see prototype examples of testing, phantom_js, validating output, screenshots, etc.  In other words, if I'm not going to use plovr for interactive development, how *should* I be doing it instead?

**Comment by achew22** [comment]
@jart I don't know if you're aware of Dash (https://github.com/bazelbuild/dash) but it might also be a good candidate for testing these rules. It would feed back into Bazel in a way that people could directly enjoy. It has a couple of nice attributes.

1.   Already exists
1.   Run on AppEngine Java
1.   Already uses Bazel

It misses on almost all the other points you mentioned, but I think they would be happy to take pull requests. It is also nice in that the data isn't permanent. If you were to ignore the fact that there is preexisting data I bet that no one would put up a fight.

Just a thought

**Comment by jart** [comment]
@pcj I forgot @robfig built that demo application. I'm so happy to see that both of you have taken the time to demo Closure Rules. There are a few best practices I would recommend. E.g. having one BUILD file per directory. Also @robfig you would like [this](https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/test/arithmetic_es6module_test.js). Would both of you be able to make your example projects kosher from a licensing standpoint, so I can send pull requests? Basically use the LICENSE.txt, AUTHORS, CONTRIBUTORS, and CONTRIBUTING files from this project as a template. (Also consider license headers in files.) Then I can contribute.

**Comment by jart** [comment]
@achew22 It would be so wonderful if Dash adopted Closure Rules. I filed an issue asking them. https://github.com/bazelbuild/dash/issues/17

**Comment by hochhaus** [comment]
One additional feature request for the sample app, would it be possible to use an MVP or MVC pattern where it makes sense to?

**Comment by jart** [comment]
Oh there will absolutely be a separation of concerns.

**Comment by robfig** [comment]
@jart, I'm curious about 
https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/test/arithmetic_es6module_test.js

1. I'm not familliar with the "goog:" prefix in the import - does that indicate that it should find that in closure library? 
2. Does Closure Compiler support standard ES6 modules / imports to the same extent that it supports goog.module / goog.require? E.g. I could use standard ES6 modules without any goog specific functions and get all the same goodies?

Thanks!

**Comment by jart** [comment]
@robfig (1) Correct. Except it doesn't have to just be from Closure Library. It could come from any file using traditional `goog.provide` namespaces. The goog: prefix differentiates them from ES6 module names, which are the short path without the .js extension. See this [test](https://github.com/bazelbuild/rules_closure/blob/master/closure/compiler/test/exports_and_entry_points/BUILD) to learn more. Also see the [Managing Dependencies](https://github.com/google/closure-compiler/wiki/Managing-Dependencies) docs of the Closure Compiler. (2) Correct. See the test files. I put a fair bit of work into making ES6 modules work correctly, since the new standard syntax is the future. It SHOULD work across repositories, without needing the "external/blah/" nonsense, although I haven't tested it. The only thing I don't have currently is a way to alias paths. For example, if I have a file //closure/compiler/test/suite/foo.js then I have no choice but to import it as `import "closure/compiler/test/suite/foo"`. I haven't implemented a feature yet where you can alias it to `import "foo"`. This will probably be necessary in the future.
