### ISSUE TITLE
Set --define=goog.json.USE_NATIVE_JSON by default

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#79]
At this point I think most new code should set `goog.json.USE_NATIVE_JSON` by default. The few users who need IE7- support or have specific JSON parsing needs can disable explicitly.

The tricky part about enabling it automatically in `closure_js_binary()` is that the compiler define can only be set when `goog.json` is transitively required. The skylark rule does not currently know which closure library sources will be used. Rather all closure library sources are passed to the compiler and the compiler drops the unused ones.

One idea is that we could instrument JsChecker to return the list of transitively required sources during `closure_js_library()` and then maybe `closure_js_binary()` could conditionally set the define based on that list?

What is the idiomatic approach to conditionally set defines?

**Comment by jart** [comment]
Let's absolutely enable it by default.

Handling your concern is easy. Just have the Skylark rule iterate over the labels in the transitive srcs and determine if `label.short_path` is equal to a hard-coded string of the file that declares that define.

Also keep in mind that the Skylark rule can send information to the Java JsChecker program, but not really the other way around. Skylark rules can only write files to disk. They can't read them back from a program output. Skylark rules have to maintain their own data structures.

**Comment by jart** [comment]
Also if we do this, it might be nice to at some point in the future add an `undefs` feature so the user can say: `undefs = ["--define=goog.json.USE_NATIVE_JSON=True"],` if he really wants legacy XHR support.

**Comment by hochhaus** [comment]
Thanks, that is great news.

> Handling your concern is easy. Just have the Skylark rule iterate over the
> labels in the transitive srcs and determine if label.short_path is equal to a
> hard-coded string of the file that declares that define.

Maybe I'm missing your point, but I thought that when depending on _any_ part of closure library that _all_ of the library files are included in transitive_js_srcs (vs just the subset of library files actually being transitively required). My first attempt at implementing ended up setting the define if the code being compiled used the library at all (even though it was explicitly checking for the library json.js file). I'll try again though.

To aid my understanding can you point me at the code in rules_closure that determines the subset of library files actually used?

**Comment by jart** [comment]
- https://github.com/bazelbuild/rules_closure/blob/master/closure/library/closure_library.BUILD
- https://github.com/bazelbuild/rules_closure/blob/master/closure/library/BUILD

Right now Closure Library is partitioned into three pieces:

- `base.js` which is a special snowflake automatically added to all library rules
- `//closure/library` which is all sources except those meant for testing
- `//closure/library:testing` which is everything meant for testing

Internally at Google, Closure Library actually has a `js_library` for nearly every... single... js file. Because early versions of the Closure Compiler weren't able to re-order .js files mid-compilation based on provide/require statements. It had to rely 100% on the Blaze dependency graph to order files. This ended up leading to people writing tools like GenJSDeps which would scan .js files for import statements and then generate gigantic `BUILD` files. It was a temporary hack that just never seemed to go away. Although later on, combined rules nearly identical to the Closure Rules layout I described above became available.

Tangent aside, it's probably a good idea to check for the individual file we care about. Because it's possible we might discover in a month that we need to break down our definition for Closure Library into further libraries.

**Comment by hochhaus** [comment]
Thanks for the references. That makes sense and matches my understanding.

Still, I think that I'm missing something.

Say that I have a binary for which the dependency on closure library is `goog.require('goog.object');`. As `goog.object` lives in `js_library_files` won't all of the other files in `js_library_files` also be in transitive_js_srcs?

I still can't find the code in rules_closure that subsets the files in `js_library_files` to only the transitive dependencies of files actually used for a given target. Can you point me in the correct direction?

If all files in `js_library_files` are included in transitive_js_srcs in this case then checking for json.js won't help as then goog.json.USE_NATIVE_JSON will be incorrect passed to the compiler. At least this is the bug I was seeing in my initial attempt to implement this feature. However, possible I just had done something else wrong.

**Comment by jart** [comment]
Correct. If you link `//closure/library` you're pulling in ~900 JS files into `transitive_js_srcs`. But the compiler is able to eliminate the files it doesn't need very quickly in the compilation.

`@closure_library//:js_library_files` is a red herring. That fileset exists for one reason and one reason only: so it can be added to the srcs list of [//closure/library](https://github.com/bazelbuild/rules_closure/blob/master/closure/library/BUILD#L20). When that Skylark rule gets executed, what happens is it constructs a `transitive_js_srcs` set() containing all ~900 or so js files. Then whenever a rule depends on `//closure/library`, it creates a new `transitive_js_srcs` set() containing its srcs, and those other 900. And as you go up the food chain, the set just gets bigger and bigger. Then eventually you hit a `closure_js_binary` rule. It reads the `transitive_js_srcs` from all its `deps` and puts them together into one giant set. then it writes *every single js file* out as a `--js` flag to Closure Compiler. It gives the compiler everything. The Skylark rules don't even attempt to figure out which ones are actually needed, because they can't. That's what the compiler does.

But just to make sure I'm not actually misunderstanding you—I'm operating under the assumption that so long as `--js=external/closure_library/closure/goog/json/json.js` is passed to the compiler, it is legal to pass that define flag. Even if `json.js` happens to get optimized away in that early compiler pass. Is this accurate? Or does that define actually have to be non-dead code in order for the define to work correctly? If that's the case, we might be in trouble.

**Comment by hochhaus** [comment]
Thanks for taking the time to write up that very detailed explanation. It confirms my impression that the skylark rules know about a _superset_ of the transitive closure of dependencies and the compiler knows the real transitive closure. This is the core of the problem.

> I'm operating under the assumption that so long as --js=external/closure_library/closure/goog/json/json.js is passed to the compiler, it is legal to pass that define flag. Even if json.js happens to get optimized away in that early compiler pass. Is this accurate?

Regrettably, that is incorrect. If the compiler strips away the file in the early pass, setting the define causes an error. For example:

```
ahochhaus@ahochhaus-pc:~/test2$ echo "goog.require('goog.object');" > obj.js
ahochhaus@ahochhaus-pc:~/test2$ echo "goog.require('goog.json');" > json.js
ahochhaus@ahochhaus-pc:~/test2$ java -jar compiler.jar \
    --compilation_level=ADVANCED \
    --dependency_mode=LOOSE  \
    --define=goog.json.USE_NATIVE_JSON \
    --js ~/closure-library-20160517/closure/goog/base.js \
    --js ~/closure-library-20160517/closure/goog/deps.js \
    --js ~/closure-library-20160517/closure/goog/object/object.js \
    --js ~/closure-library-20160517/closure/goog/json/json.js \
    --js obj.js
WARNING - unknown @define variable goog.json.USE_NATIVE_JSON

0 error(s), 1 warning(s)

ahochhaus@ahochhaus-pc:~/test2$ java -jar compiler.jar \
    --compilation_level=ADVANCED \
    --dependency_mode=LOOSE  \
    --define=goog.json.USE_NATIVE_JSON \
    --js ~/closure-library-20160517/closure/goog/base.js \
    --js ~/closure-library-20160517/closure/goog/deps.js \
    --js ~/closure-library-20160517/closure/goog/object/object.js \
    --js ~/closure-library-20160517/closure/goog/json/json.js \
    --js json.js 

ahochhaus@ahochhaus-pc:~/test2$ echo $?
0
```

> Or does that define actually have to be non-dead code in order for the define to work correctly? If that's the case, we might be in trouble.

Yes, that is the case.

This is why I was contemplating the idea of having JsChecker compute the (real) transitive closure of deps and pass that back to bazel/skylark (maybe via an on disk file). Then at the point that the binary is being built we could use that tighter set of dependencies to conditionally set `--defines`. It sounds like that idea isn't feasible.

I have three other ideas:
- Modify the compiler to process defines prior to dropping unused sources (but this likely has negative performance implications of needing to fully parse each source file)
- Modify the compiler to not error if unknown defines are set (this likely has no negative performance implications but also hides unknown --defines being passed)
- Break out closure library at the skylark level into a very fine grained set of dependencies (similar to what you mentioned -- one per file) such that skylark itself knows about which sources are actually used.

All of those options sound bad though. Maybe it is best to just mark this as WONTFIX and have the users setup their own defines.

What are your thoughts?

**Comment by jart** [comment]
I wouldn't call the provide/require graph "real." The build rule graph is also a legit transitive closure. It's just sort of thicker grained. Just like how the provide/require graph is thicker grained than the actual JS call flow graph.

There's value to having the build graph be thicker grained. Because if it wasn't, then it'd basically just be a arduous repetition of the provides/requires, which is far too much of a burden.

> Regrettably, that is incorrect. If the compiler strips away the file in the early pass, setting the define causes an error. For example:

Then we definitely know there's no way for us to abstract these defines for the user, without the suggestions you made.

> All of those options sound bad though. Maybe it is best to just mark this as WONTFIX and have the users setup their own defines.

I still think there's a lot of value in what you're trying to do. We might not be able to fix it now, but we should definitely do it in the near future when we can.

> Modify the compiler to not error if unknown defines are set (this likely has no negative performance implications but also hides unknown --defines being passed)

I like this proposal the best. But we should probably do it in our own frontend to the compiler. We're going to build a JsCompiler.java program for other reasons too, just like we built JsChecker.java. So I guess this is just one more reason why we should do that sooner rather than later.

**Comment by hochhaus** [comment]
> I wouldn't call the provide/require graph "real." The build rule graph is also a legit transitive closure. It's just sort of thicker grained. Just like how the provide/require graph is thicker grained than the actual JS call flow graph.

That is a good point.

> We're going to build a JsCompiler.java program for other reasons too, just like we built JsChecker.java. So I guess this is just one more reason why we should do that sooner rather than later.

Sounds good.

Thanks again for your time and help.

**Comment by hochhaus** [comment]
If we are building our own frontend one idea is to add two flags (for example `--define` and `--define_internal`). When rules_closure sets up defines it could use `--define_internal` which does not generate the error on unknown define. However, when users pass their own `--define` (via `defs`) they get the current behavior of the compiler. This is maybe as close as is practical to the ideal behavior.

**Comment by jart** [comment]
> Thanks again for your time and help.

And thank you for yours. I think the work we've been doing is going to pay dividends for a lot of developers in the future. So I'm really grateful that you're helping me perform this service to the open source community. I want the highest quality JavaScript tools Googlers have enjoyed for many years to be available to everyone.

> If we are building our own frontend one idea is to add two flags (for example --define and --define_internal). When rules_closure sets up defines it could use --define_internal which does not generate the error on unknown define. However, when users pass their own --define (via defs) they get the current behavior of the compiler. This is maybe as close as is practical to the ideal behavior.

SGTM

**Comment by hochhaus** [comment]
That is a cool idea worth more consideration. One downside is that both rules_closure specified defines and user specified defines would be not be validated. If user specified defines do not exist or are not in goog.require/provide dependency graph it is desired behavior to get the error IMO.

Another thought that I just had. In our custom front end could we just whitelist the defines that we know will be set by rules_closure?

**Comment by jart** [comment]
Yes we could do anything.

But here's what I would suggest for now. Maybe just disable unknownDefines check entirely. Then maybe we can contribute a feature to mainline Closure Compiler called `--define_force` or something like that.

**Comment by hochhaus** [comment]
Ah, I see your point. Yes, I like it. That allows this feature to be implemented now.
